Repository suankularb-wittayalai-school/mysk-frontend, pull requests merged in 2022-05, with the labels that each got.

#23 Refactor: types translator
  src/components/dialogs/EditPerson.tsx
  src/pages/s/home.tsx
  src/pages/t/admin/index.tsx
  src/pages/t/admin/students.tsx
  src/pages/t/admin/teachers.tsx
  src/pages/t/home.tsx
  src/utils/backend/contact/index.ts
  src/utils/backend/database.ts
  src/utils/backend/person/person.ts
  src/utils/backend/person/student.ts
  src/utils/backend/person/teacher.ts
  src/utils/hooks/auth.ts
  src/utils/types/database/contact.ts
  src/utils/types/database/person.ts
  src/utils/types/database/subject.ts
  src/utils/types/person.ts
Labels: type: enhancement, type: refactor, size: medium large

#29 Hotfix: Vercel i18n
  next-i18next.config.js
  public/static/locales/en-US/about.json
  public/static/locales/en-US/account.json
  public/static/locales/en-US/admin.json
  public/static/locales/en-US/class.json
  public/static/locales/en-US/common.json
  public/static/locales/en-US/dashboard.json
  public/static/locales/en-US/error.json
  public/static/locales/en-US/landing.json
  public/static/locales/en-US/news.json
  public/static/locales/en-US/schedule.json
  public/static/locales/en-US/subjects.json
  public/static/locales/en-US/teacher.json
  public/static/locales/th/about.json
  public/static/locales/th/account.json
  public/static/locales/th/admin.json
  public/static/locales/th/class.json
  public/static/locales/th/common.json
  public/static/locales/th/dashboard.json
  public/static/locales/th/error.json
  public/static/locales/th/landing.json
  public/static/locales/th/news.json
  public/static/locales/th/schedule.json
  public/static/locales/th/subjects.json
  public/static/locales/th/teacher.json
Labels: type: bug, size: small

#32 Import Data Dialog
  public/site.webmanifest
  public/static/locales/en-US/account.json
  public/static/locales/en-US/admin.json
  public/static/locales/th/account.json
  public/static/locales/th/admin.json
  src/components/dialogs/ChangePassword.tsx
  src/components/dialogs/EditPerson.tsx
  src/components/dialogs/GenerateClasses.tsx
  src/components/dialogs/ImportData.tsx
  src/pages/_document.tsx
  src/pages/account/login.tsx
  src/pages/index.tsx
  src/pages/s/home.tsx
  src/pages/t/admin/classes.tsx
  src/pages/t/admin/index.tsx
  src/pages/t/admin/students.tsx
  src/pages/t/admin/subjects.tsx
  src/pages/t/admin/teachers.tsx
  src/pages/t/home.tsx
  src/utils/types/common.ts
  src/utils/types/person.ts
  src/utils/types/schedule.ts
Labels: type: enhancement, size: medium small

#33 Refactor: Landing
  package-lock.json
  package.json
  public/images/landing.png
  public/images/landing.webp
  src/components/Layout.tsx
  src/pages/index.tsx
  src/utils/animations/config.ts
Labels: type: enhancement, size: medium small
